name: CI/CD
on: [push, pull_request, workflow_dispatch]
jobs:
  job:
    permissions: write-all
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Build
      run: dotnet build
    - name: Build nuget
      if: github.event_name == 'workflow_dispatch'
      run: dotnet pack PolyMod.csproj -o nuget
    - name: Deploy nuget
      if: github.event_name == 'workflow_dispatch_testmodebtw'
      run: dotnet nuget push -s https://polymod.dev/nuget/v3/index.json -k ${{ secrets.KEY }} nuget/*.nupkg
    - name: Get version
      if: github.event_name == 'workflow_dispatch'
      id: version
      uses: kzrnm/get-net-sdk-project-versions-action@v2
      with:
          proj-path: PolyMod.csproj
    - name: Check if pre-release
      if: github.event_name == 'workflow_dispatch'
      run: |
        if [[ "${{ steps.version.outputs.version }}" == *"-"* ]]; then
          echo "pre_release=true" >> $GITHUB_ENV
        else
          echo "pre_release=false" >> $GITHUB_ENV
        fi
    - name: Deploy release
      if: github.event_name == 'workflow_dispatch'
      run: gh release create v${{ steps.version.outputs.version }} bin/IL2CPP/net6.0/PolyMod.dll
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
